$(function() {
    GREEN.display_character('h', 'row5', true);
    GREEN.display_character(' ', 'basics-0', true);
    GREEN.display_character('e', 'basics-1', true);
    GREEN.display_character('t', 'basics-2', true);
    GREEN.display_character('a', 'basics-3', true);
    GREEN.display_word('sos', 'rowsos', true);
    GREEN.display_character('0', 'digits-row');
    GREEN.display_character('1', 'digits-row');
    GREEN.display_character('2', 'digits-row');
    GREEN.display_character('3', 'digits-row');
    GREEN.display_character('4', 'digits-row');
    GREEN.display_character('5', 'digits-row');
    GREEN.display_character('6', 'digits-row');
    GREEN.display_character('7', 'digits-row');
    GREEN.display_character('8', 'digits-row');
    GREEN.display_character('9', 'digits-row');
    GREEN.display_character('a', 'letters-0');
    GREEN.display_character('b', 'letters-0');
    GREEN.display_character('c', 'letters-0');
    GREEN.display_character('d', 'letters-0');
    GREEN.display_character('e', 'letters-0');
    GREEN.display_character('f', 'letters-0');
    GREEN.display_character('g', 'letters-0');
    GREEN.display_character('h', 'letters-0');
    GREEN.display_character('i', 'letters-0');
    GREEN.display_character('j', 'letters-0');
    GREEN.display_character('k', 'letters-0');
    GREEN.display_character('l', 'letters-1');
    GREEN.display_character('m', 'letters-1');
    GREEN.display_character('n', 'letters-1');
    GREEN.display_character('o', 'letters-1');
    GREEN.display_character('p', 'letters-1');
    GREEN.display_character('q', 'letters-1');
    GREEN.display_character('r', 'letters-1');
    GREEN.display_character('s', 'letters-1');
    GREEN.display_character('t', 'letters-1');
    GREEN.display_character('u', 'letters-1');
    GREEN.display_character('v', 'letters-1');
    GREEN.display_character('w', 'letters-2');
    GREEN.display_character('x', 'letters-2');
    GREEN.display_character('y', 'letters-2');
    GREEN.display_character('z', 'letters-2');
});
